In [1]:
#!pip3 install twilio

In [2]:
#!pip3 install pandas

In [3]:
#!pip3 install tqdm

In [4]:
import sys
print(sys.executable)

!{sys.executable} -m pip show twilio

/home/ingdavidhoyosgil/anaconda3/envs/de_weather/bin/python
Name: twilio
Version: 9.10.9
Summary: Twilio API client and TwiML generator
Home-page: https://github.com/twilio/twilio-python/
Author: Twilio
Author-email:
License: MIT
Location: /home/ingdavidhoyosgil/anaconda3/envs/de_weather/lib/python3.14/site-packages
Requires: aiohttp, aiohttp-retry, PyJWT, requests
Required-by:

In [5]:
import twilio_config
print(dir(twilio_config))

['API_KEY_WAPI', 'PHONE_NUMBER', 'PRIVATE_NUMBER', 'TWILIO_ACCOUNT_SID', 'TWILIO_AUTH_TOKEN', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__']

In [6]:
import os
from twilio.rest import Client
from twilio_config import TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN, PRIVATE_NUMBER, API_KEY_WAPI
import time

from requests import Request, Session
from requests.exceptions import ConnectionError, Timeout, TooManyRedirects
import json

import pandas as pd
import requests
from bs4 import BeautifulSoup
from tqdm import tqdm

from datetime import datetime

## URL

In [7]:
query = 'Buenaventura'
api_key = API_KEY_WAPI

url_weather = 'https://api.weatherapi.com/v1/forecast.json?key='+api_key+'&q='+query+'&days=1&aqi=no&alerts=no'

In [8]:
response = requests.get(url_weather).json()

In [9]:
response

{'location': {'name': 'Buenaventura',
  'region': 'Valle del Cauca',
  'country': 'Colombia',
  'lat': 3.8933,
  'lon': -77.0697,
  'tz_id': 'America/Bogota',
  'localtime_epoch': 1784500922,
  'localtime': '2026-07-19 17:42'},
 'current': {'last_updated_epoch': 1784500200,
  'last_updated': '2026-07-19 17:30',
  'temp_c': 26.2,
  'temp_f': 79.2,
  'is_day': 1,
  'condition': {'text': 'Partly cloudy',
   'icon': '//cdn.weatherapi.com/weather/64x64/day/116.png',
   'code': 1003},
  'wind_mph': 2.9,
  'wind_kph': 4.7,
  'wind_degree': 203,
  'wind_dir': 'SSW',
  'pressure_mb': 1009.0,
  'pressure_in': 29.8,
  'precip_mm': 1.1,
  'precip_in': 0.04,
  'humidity': 94,
  'cloud': 50,
  'feelslike_c': 30.1,
  'feelslike_f': 86.2,
  'windchill_c': 25.5,
  'windchill_f': 78.0,
  'heatindex_c': 28.8,
  'heatindex_f': 83.9,
  'dewpoint_c': 24.0,
  'dewpoint_f': 75.3,
  'vis_km': 10.0,
  'vis_miles': 6.0,
  'uv': 0.3,
  'gust_mph': 4.1,
  'gust_kph': 6.7,
  'will_it_rain': 1,
  'chance_of_rain': 74,
  'will_it_snow': 0,
  'chance_of_snow': 0,
  'short_rad': 241.87,
  'diff_rad': 141.26,
  'dni': 4.37,
  'gti': 241.73},
 'forecast': {'forecastday': [{'date': '2026-07-19',
    'date_epoch': 1784419200,
    'day': {'maxtemp_c': 27.3,
     'maxtemp_f': 81.1,
     'mintemp_c': 23.7,
     'mintemp_f': 74.6,
     'avgtemp_c': 24.9,
     'avgtemp_f': 76.8,
     'maxwind_mph': 7.2,
     'maxwind_kph': 11.5,
     'totalprecip_mm': 24.59,
     'totalprecip_in': 0.97,
     'totalsnow_cm': 0.0,
     'avgvis_km': 9.9,
     'avgvis_miles': 6.0,
     'avghumidity': 92,
     'daily_will_it_rain': 1,
     'daily_chance_of_rain': 90,
     'daily_will_it_snow': 0,
     'daily_chance_of_snow': 0,
     'condition': {'text': 'Light rain shower',
      'icon': '//cdn.weatherapi.com/weather/64x64/day/353.png',
      'code': 1240},
     'uv': 7.1},
    'astro': {'sunrise': '06:05 AM',
     'sunset': '06:24 PM',
     'moonrise': '10:35 AM',
     'moonset': '10:54 PM',
     'moon_phase': 'First Quarter',
     'moon_illumination': 33,
     'is_moon_up': 1,
     'is_sun_up': 1},
    'hour': [{'time_epoch': 1784437200,
      'time': '2026-07-19 00:00',
      'temp_c': 23.9,
      'temp_f': 75.0,
      'is_day': 0,
      'condition': {'text': 'Light rain shower',
       'icon': '//cdn.weatherapi.com/weather/64x64/night/353.png',
       'code': 1240},
      'wind_mph': 2.5,
      'wind_kph': 4.0,
      'wind_degree': 136,
      'wind_dir': 'SE',
      'pressure_mb': 1011.0,
      'pressure_in': 29.85,
      'precip_mm': 0.5,
      'precip_in': 0.02,
      'snow_cm': 0.0,
      'humidity': 93,
      'cloud': 92,
      'feelslike_c': 26.4,
      'feelslike_f': 79.5,
      'windchill_c': 23.9,
      'windchill_f': 75.0,
      'heatindex_c': 26.4,
      'heatindex_f': 79.5,
      'dewpoint_c': 22.8,
      'dewpoint_f': 73.0,
      'will_it_rain': 0,
      'chance_of_rain': 62,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 10.0,
      'vis_miles': 6.0,
      'gust_mph': 4.5,
      'gust_kph': 7.2,
      'uv': 0,
      'short_rad': 0,
      'diff_rad': 0,
      'dni': 0,
      'gti': 0},
     {'time_epoch': 1784440800,
      'time': '2026-07-19 01:00',
      'temp_c': 23.8,
      'temp_f': 74.9,
      'is_day': 0,
      'condition': {'text': 'Cloudy',
       'icon': '//cdn.weatherapi.com/weather/64x64/night/119.png',
       'code': 1006},
      'wind_mph': 2.9,
      'wind_kph': 4.7,
      'wind_degree': 152,
      'wind_dir': 'SSE',
      'pressure_mb': 1010.0,
      'pressure_in': 29.83,
      'precip_mm': 0.0,
      'precip_in': 0.0,
      'snow_cm': 0.0,
      'humidity': 93,
      'cloud': 77,
      'feelslike_c': 26.3,
      'feelslike_f': 79.3,
      'windchill_c': 23.8,
      'windchill_f': 74.9,
      'heatindex_c': 26.3,
      'heatindex_f': 79.3,
      'dewpoint_c': 22.7,
      'dewpoint_f': 72.8,
      'will_it_rain': 0,
      'chance_of_rain': 26,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 10.0,
      'vis_miles': 6.0,
      'gust_mph': 5.3,
      'gust_kph': 8.5,
      'uv': 0,
      'short_rad': 0,
      'diff_rad': 0,
      'dni': 0,
      'gti': 0},
     {'time_epoch': 1784444400,
      'time': '2026-07-19 02:00',
      'temp_c': 23.7,
      'temp_f': 74.7,
      'is_day': 0,
      'condition': {'text': 'Cloudy',
       'icon': '//cdn.weatherapi.com/weather/64x64/night/119.png',
       'code': 1006},
      'wind_mph': 2.7,
      'wind_kph': 4.3,
      'wind_degree': 167,
      'wind_dir': 'SSE',
      'pressure_mb': 1010.0,
      'pressure_in': 29.81,
      'precip_mm': 0.0,
      'precip_in': 0.0,
      'snow_cm': 0.0,
      'humidity': 93,
      'cloud': 73,
      'feelslike_c': 26.1,
      'feelslike_f': 79.0,
      'windchill_c': 23.7,
      'windchill_f': 74.7,
      'heatindex_c': 26.1,
      'heatindex_f': 79.0,
      'dewpoint_c': 22.5,
      'dewpoint_f': 72.5,
      'will_it_rain': 0,
      'chance_of_rain': 25,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 10.0,
      'vis_miles': 6.0,
      'gust_mph': 4.9,
      'gust_kph': 7.9,
      'uv': 0,
      'short_rad': 0,
      'diff_rad': 0,
      'dni': 0,
      'gti': 0},
     {'time_epoch': 1784448000,
      'time': '2026-07-19 03:00',
      'temp_c': 23.8,
      'temp_f': 74.9,
      'is_day': 0,
      'condition': {'text': 'Patchy rain nearby',
       'icon': '//cdn.weatherapi.com/weather/64x64/night/176.png',
       'code': 1063},
      'wind_mph': 2.2,
      'wind_kph': 3.6,
      'wind_degree': 178,
      'wind_dir': 'S',
      'pressure_mb': 1009.0,
      'pressure_in': 29.8,
      'precip_mm': 0.01,
      'precip_in': 0.0,
      'snow_cm': 0.0,
      'humidity': 93,
      'cloud': 73,
      'feelslike_c': 26.3,
      'feelslike_f': 79.3,
      'windchill_c': 23.8,
      'windchill_f': 74.9,
      'heatindex_c': 26.3,
      'heatindex_f': 79.3,
      'dewpoint_c': 22.6,
      'dewpoint_f': 72.7,
      'will_it_rain': 0,
      'chance_of_rain': 26,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 10.0,
      'vis_miles': 6.0,
      'gust_mph': 4.0,
      'gust_kph': 6.4,
      'uv': 0,
      'short_rad': 0,
      'diff_rad': 0,
      'dni': 0,
      'gti': 0},
     {'time_epoch': 1784451600,
      'time': '2026-07-19 04:00',
      'temp_c': 23.8,
      'temp_f': 74.9,
      'is_day': 0,
      'condition': {'text': 'Light rain shower',
       'icon': '//cdn.weatherapi.com/weather/64x64/night/353.png',
       'code': 1240},
      'wind_mph': 5.8,
      'wind_kph': 9.4,
      'wind_degree': 189,
      'wind_dir': 'S',
      'pressure_mb': 1009.0,
      'pressure_in': 29.79,
      'precip_mm': 0.45,
      'precip_in': 0.02,
      'snow_cm': 0.0,
      'humidity': 95,
      'cloud': 93,
      'feelslike_c': 26.4,
      'feelslike_f': 79.4,
      'windchill_c': 23.8,
      'windchill_f': 74.9,
      'heatindex_c': 26.4,
      'heatindex_f': 79.4,
      'dewpoint_c': 23.0,
      'dewpoint_f': 73.3,
      'will_it_rain': 0,
      'chance_of_rain': 60,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 10.0,
      'vis_miles': 6.0,
      'gust_mph': 9.8,
      'gust_kph': 15.7,
      'uv': 0,
      'short_rad': 0,
      'diff_rad': 0,
      'dni': 0,
      'gti': 0},
     {'time_epoch': 1784455200,
      'time': '2026-07-19 05:00',
      'temp_c': 23.8,
      'temp_f': 74.8,
      'is_day': 0,
      'condition': {'text': 'Light rain shower',
       'icon': '//cdn.weatherapi.com/weather/64x64/night/353.png',
       'code': 1240},
      'wind_mph': 4.7,
      'wind_kph': 7.6,
      'wind_degree': 187,
      'wind_dir': 'S',
      'pressure_mb': 1009.0,
      'pressure_in': 29.8,
      'precip_mm': 0.68,
      'precip_in': 0.03,
      'snow_cm': 0.0,
      'humidity': 95,
      'cloud': 89,
      'feelslike_c': 26.3,
      'feelslike_f': 79.4,
      'windchill_c': 23.8,
      'windchill_f': 74.8,
      'heatindex_c': 26.3,
      'heatindex_f': 79.4,
      'dewpoint_c': 23.0,
      'dewpoint_f': 73.3,
      'will_it_rain': 0,
      'chance_of_rain': 66,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 10.0,
      'vis_miles': 6.0,
      'gust_mph': 7.8,
      'gust_kph': 12.5,
      'uv': 0,
      'short_rad': 0,
      'diff_rad': 0,
      'dni': 0,
      'gti': 0},
     {'time_epoch': 1784458800,
      'time': '2026-07-19 06:00',
      'temp_c': 23.7,
      'temp_f': 74.6,
      'is_day': 0,
      'condition': {'text': 'Light rain shower',
       'icon': '//cdn.weatherapi.com/weather/64x64/night/353.png',
       'code': 1240},
      'wind_mph': 4.5,
      'wind_kph': 7.2,
      'wind_degree': 174,
      'wind_dir': 'S',
      'pressure_mb': 1010.0,
      'pressure_in': 29.81,
      'precip_mm': 1.47,
      'precip_in': 0.06,
      'snow_cm': 0.0,
      'humidity': 95,
      'cloud': 100,
      'feelslike_c': 26.1,
      'feelslike_f': 79.1,
      'windchill_c': 23.7,
      'windchill_f': 74.6,
      'heatindex_c': 26.1,
      'heatindex_f': 79.1,
      'dewpoint_c': 22.8,
      'dewpoint_f': 73.0,
      'will_it_rain': 1,
      'chance_of_rain': 79,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 10.0,
      'vis_miles': 6.0,
      'gust_mph': 8.1,
      'gust_kph': 13.1,
      'uv': 0,
      'short_rad': 0,
      'diff_rad': 0,
      'dni': 0,
      'gti': 0},
     {'time_epoch': 1784462400,
      'time': '2026-07-19 07:00',
      'temp_c': 24.1,
      'temp_f': 75.3,
      'is_day': 1,
      'condition': {'text': 'Light rain shower',
       'icon': '//cdn.weatherapi.com/weather/64x64/day/353.png',
       'code': 1240},
      'wind_mph': 2.7,
      'wind_kph': 4.3,
      'wind_degree': 174,
      'wind_dir': 'S',
      'pressure_mb': 1010.0,
      'pressure_in': 29.83,
      'precip_mm': 1.07,
      'precip_in': 0.04,
      'snow_cm': 0.0,
      'humidity': 95,
      'cloud': 93,
      'feelslike_c': 26.7,
      'feelslike_f': 80.0,
      'windchill_c': 24.1,
      'windchill_f': 75.3,
      'heatindex_c': 26.7,
      'heatindex_f': 80.0,
      'dewpoint_c': 23.1,
      'dewpoint_f': 73.7,
      'will_it_rain': 1,
      'chance_of_rain': 75,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 10.0,
      'vis_miles': 6.0,
      'gust_mph': 4.5,
      'gust_kph': 7.3,
      'uv': 0.4,
      'short_rad': 2.06,
      'diff_rad': 1.16,
      'dni': 0.0,
      'gti': 0.0},
     {'time_epoch': 1784466000,
      'time': '2026-07-19 08:00',
      'temp_c': 25.1,
      'temp_f': 77.2,
      'is_day': 1,
      'condition': {'text': 'Light rain shower',
       'icon': '//cdn.weatherapi.com/weather/64x64/day/353.png',
       'code': 1240},
      'wind_mph': 3.8,
      'wind_kph': 6.1,
      'wind_degree': 186,
      'wind_dir': 'S',
      'pressure_mb': 1011.0,
      'pressure_in': 29.84,
      'precip_mm': 0.23,
      'precip_in': 0.01,
      'snow_cm': 0.0,
      'humidity': 93,
      'cloud': 72,
      'feelslike_c': 28.2,
      'feelslike_f': 82.7,
      'windchill_c': 25.1,
      'windchill_f': 77.2,
      'heatindex_c': 28.2,
      'heatindex_f': 82.7,
      'dewpoint_c': 23.8,
      'dewpoint_f': 74.9,
      'will_it_rain': 0,
      'chance_of_rain': 41,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 10.0,
      'vis_miles': 6.0,
      'gust_mph': 5.1,
      'gust_kph': 8.2,
      'uv': 1.3,
      'short_rad': 134.26,
      'diff_rad': 73.43,
      'dni': 0.0,
      'gti': 0.0},
     {'time_epoch': 1784469600,
      'time': '2026-07-19 09:00',
      'temp_c': 26.0,
      'temp_f': 78.8,
      'is_day': 1,
      'condition': {'text': 'Light rain shower',
       'icon': '//cdn.weatherapi.com/weather/64x64/day/353.png',
       'code': 1240},
      'wind_mph': 4.5,
      'wind_kph': 7.2,
      'wind_degree': 214,
      'wind_dir': 'SW',
      'pressure_mb': 1011.0,
      'pressure_in': 29.85,
      'precip_mm': 0.52,
      'precip_in': 0.02,
      'snow_cm': 0.0,
      'humidity': 89,
      'cloud': 76,
      'feelslike_c': 29.5,
      'feelslike_f': 85.0,
      'windchill_c': 26.0,
      'windchill_f': 78.8,
      'heatindex_c': 29.5,
      'heatindex_f': 85.0,
      'dewpoint_c': 24.1,
      'dewpoint_f': 75.3,
      'will_it_rain': 0,
      'chance_of_rain': 55,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 10.0,
      'vis_miles': 6.0,
      'gust_mph': 6.1,
      'gust_kph': 9.9,
      'uv': 3.5,
      'short_rad': 224.98,
      'diff_rad': 121.89,
      'dni': 0.0,
      'gti': 0.0},
     {'time_epoch': 1784473200,
      'time': '2026-07-19 10:00',
      'temp_c': 27.0,
      'temp_f': 80.6,
      'is_day': 1,
      'condition': {'text': 'Light rain shower',
       'icon': '//cdn.weatherapi.com/weather/64x64/day/353.png',
       'code': 1240},
      'wind_mph': 5.4,
      'wind_kph': 8.6,
      'wind_degree': 221,
      'wind_dir': 'SW',
      'pressure_mb': 1011.0,
      'pressure_in': 29.87,
      'precip_mm': 1.73,
      'precip_in': 0.07,
      'snow_cm': 0.0,
      'humidity': 85,
      'cloud': 56,
      'feelslike_c': 31.0,
      'feelslike_f': 87.8,
      'windchill_c': 27.0,
      'windchill_f': 80.6,
      'heatindex_c': 31.0,
      'heatindex_f': 87.8,
      'dewpoint_c': 24.4,
      'dewpoint_f': 75.8,
      'will_it_rain': 0,
      'chance_of_rain': 65,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 10.0,
      'vis_miles': 6.0,
      'gust_mph': 8.8,
      'gust_kph': 14.2,
      'uv': 6.0,
      'short_rad': 322.56,
      'diff_rad': 168.88,
      'dni': 9.57,
      'gti': 322.44},
     {'time_epoch': 1784476800,
      'time': '2026-07-19 11:00',
      'temp_c': 27.3,
      'temp_f': 81.1,
      'is_day': 1,
      'condition': {'text': 'Light rain shower',
       'icon': '//cdn.weatherapi.com/weather/64x64/day/353.png',
       'code': 1240},
      'wind_mph': 6.3,
      'wind_kph': 10.1,
      'wind_degree': 225,
      'wind_dir': 'SW',
      'pressure_mb': 1011.0,
      'pressure_in': 29.85,
      'precip_mm': 1.0,
      'precip_in': 0.04,
      'snow_cm': 0.0,
      'humidity': 83,
      'cloud': 61,
      'feelslike_c': 31.3,
      'feelslike_f': 88.4,
      'windchill_c': 27.3,
      'windchill_f': 81.1,
      'heatindex_c': 31.3,
      'heatindex_f': 88.4,
      'dewpoint_c': 24.3,
      'dewpoint_f': 75.7,
      'will_it_rain': 0,
      'chance_of_rain': 59,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 10.0,
      'vis_miles': 6.0,
      'gust_mph': 10.8,
      'gust_kph': 17.3,
      'uv': 6.8,
      'short_rad': 364.75,
      'diff_rad': 194.97,
      'dni': 16.88,
      'gti': 364.73},
     {'time_epoch': 1784480400,
      'time': '2026-07-19 12:00',
      'temp_c': 26.9,
      'temp_f': 80.5,
      'is_day': 1,
      'condition': {'text': 'Light rain shower',
       'icon': '//cdn.weatherapi.com/weather/64x64/day/353.png',
       'code': 1240},
      'wind_mph': 7.2,
      'wind_kph': 11.5,
      'wind_degree': 246,
      'wind_dir': 'WSW',
      'pressure_mb': 1011.0,
      'pressure_in': 29.85,
      'precip_mm': 1.91,
      'precip_in': 0.08,
      'snow_cm': 0.0,
      'humidity': 87,
      'cloud': 77,
      'feelslike_c': 31.0,
      'feelslike_f': 87.8,
      'windchill_c': 26.9,
      'windchill_f': 80.5,
      'heatindex_c': 31.0,
      'heatindex_f': 87.8,
      'dewpoint_c': 24.5,
      'dewpoint_f': 76.2,
      'will_it_rain': 1,
      'chance_of_rain': 72,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 10.0,
      'vis_miles': 6.0,
      'gust_mph': 13.7,
      'gust_kph': 22.0,
      'uv': 7.1,
      'short_rad': 380.93,
      'diff_rad': 206.93,
      'dni': 20.95,
      'gti': 380.97},
     {'time_epoch': 1784484000,
      'time': '2026-07-19 13:00',
      'temp_c': 26.5,
      'temp_f': 79.8,
      'is_day': 1,
      'condition': {'text': 'Light rain shower',
       'icon': '//cdn.weatherapi.com/weather/64x64/day/353.png',
       'code': 1240},
      'wind_mph': 5.8,
      'wind_kph': 9.4,
      'wind_degree': 244,
      'wind_dir': 'WSW',
      'pressure_mb': 1010.0,
      'pressure_in': 29.83,
      'precip_mm': 1.74,
      'precip_in': 0.07,
      'snow_cm': 0.0,
      'humidity': 88,
      'cloud': 75,
      'feelslike_c': 30.4,
      'feelslike_f': 86.7,
      'windchill_c': 26.5,
      'windchill_f': 79.8,
      'heatindex_c': 30.4,
      'heatindex_f': 86.7,
      'dewpoint_c': 24.4,
      'dewpoint_f': 75.9,
      'will_it_rain': 1,
      'chance_of_rain': 71,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 10.0,
      'vis_miles': 6.0,
      'gust_mph': 11.4,
      'gust_kph': 18.4,
      'uv': 5.8,
      'short_rad': 384.45,
      'diff_rad': 211.26,
      'dni': 21.94,
      'gti': 384.5},
     {'time_epoch': 1784487600,
      'time': '2026-07-19 14:00',
      'temp_c': 26.3,
      'temp_f': 79.3,
      'is_day': 1,
      'condition': {'text': 'Light rain shower',
       'icon': '//cdn.weatherapi.com/weather/64x64/day/353.png',
       'code': 1240},
      'wind_mph': 4.9,
      'wind_kph': 7.9,
      'wind_degree': 237,
      'wind_dir': 'WSW',
      'pressure_mb': 1010.0,
      'pressure_in': 29.81,
      'precip_mm': 1.68,
      'precip_in': 0.07,
      'snow_cm': 0.0,
      'humidity': 89,
      'cloud': 86,
      'feelslike_c': 30.0,
      'feelslike_f': 85.9,
      'windchill_c': 26.3,
      'windchill_f': 79.3,
      'heatindex_c': 30.0,
      'heatindex_f': 85.9,
      'dewpoint_c': 24.3,
      'dewpoint_f': 75.8,
      'will_it_rain': 1,
      'chance_of_rain': 74,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 10.0,
      'vis_miles': 6.0,
      'gust_mph': 7.1,
      'gust_kph': 11.4,
      'uv': 4.1,
      'short_rad': 385.22,
      'diff_rad': 224.26,
      'dni': 22.16,
      'gti': 385.28},
     {'time_epoch': 1784491200,
      'time': '2026-07-19 15:00',
      'temp_c': 26.1,
      'temp_f': 78.9,
      'is_day': 1,
      'condition': {'text': 'Light rain shower',
       'icon': '//cdn.weatherapi.com/weather/64x64/day/353.png',
       'code': 1240},
      'wind_mph': 4.3,
      'wind_kph': 6.8,
      'wind_degree': 229,
      'wind_dir': 'SW',
      'pressure_mb': 1009.0,
      'pressure_in': 29.79,
      'precip_mm': 1.64,
      'precip_in': 0.06,
      'snow_cm': 0.0,
      'humidity': 90,
      'cloud': 86,
      'feelslike_c': 29.6,
      'feelslike_f': 85.3,
      'windchill_c': 26.1,
      'windchill_f': 78.9,
      'heatindex_c': 29.6,
      'heatindex_f': 85.3,
      'dewpoint_c': 24.2,
      'dewpoint_f': 75.6,
      'will_it_rain': 1,
      'chance_of_rain': 74,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 10.0,
      'vis_miles': 6.0,
      'gust_mph': 5.8,
      'gust_kph': 9.4,
      'uv': 2.5,
      'short_rad': 337.04,
      'diff_rad': 197.13,
      'dni': 11.59,
      'gti': 336.94},
     {'time_epoch': 1784494800,
      'time': '2026-07-19 16:00',
      'temp_c': 25.8,
      'temp_f': 78.5,
      'is_day': 1,
      'condition': {'text': 'Light rain shower',
       'icon': '//cdn.weatherapi.com/weather/64x64/day/353.png',
       'code': 1240},
      'wind_mph': 3.4,
      'wind_kph': 5.4,
      'wind_degree': 217,
      'wind_dir': 'SW',
      'pressure_mb': 1009.0,
      'pressure_in': 29.79,
      'precip_mm': 1.43,
      'precip_in': 0.06,
      'snow_cm': 0.0,
      'humidity': 90,
      'cloud': 94,
      'feelslike_c': 29.3,
      'feelslike_f': 84.7,
      'windchill_c': 25.9,
      'windchill_f': 78.5,
      'heatindex_c': 29.3,
      'heatindex_f': 84.7,
      'dewpoint_c': 24.2,
      'dewpoint_f': 75.5,
      'will_it_rain': 1,
      'chance_of_rain': 75,
      'will_it_snow': 0,
      'chance_of_snow': 0,
      'vis_km': 10.0,
      'vis_miles': 6.0,
      'gust_mph': 6.1,
      'gust_kph': 9.9,
      'uv': 1.1,
      'short_rad': 288.3,
      'diff_rad': 168.62,
      'dni': 6.42,
      'gti': 288.15},
     {'time_epoch': 1784498400,
      'time': '2026-07-19 17:00',
      'temp_c': 26.2,
      'temp_f': 79.2,
      'is_day': 1,
      'condition': {'text': 'Partly cloudy',

In [10]:
response.keys()

dict_keys(['location', 'current', 'forecast'])

In [11]:
response['forecast']

{'forecastday': [{'date': '2026-07-19',
   'date_epoch': 1784419200,
   'day': {'maxtemp_c': 27.3,
    'maxtemp_f': 81.1,
    'mintemp_c': 23.7,
    'mintemp_f': 74.6,
    'avgtemp_c': 24.9,
    'avgtemp_f': 76.8,
    'maxwind_mph': 7.2,
    'maxwind_kph': 11.5,
    'totalprecip_mm': 24.59,
    'totalprecip_in': 0.97,
    'totalsnow_cm': 0.0,
    'avgvis_km': 9.9,
    'avgvis_miles': 6.0,
    'avghumidity': 92,
    'daily_will_it_rain': 1,
    'daily_chance_of_rain': 90,
    'daily_will_it_snow': 0,
    'daily_chance_of_snow': 0,
    'condition': {'text': 'Light rain shower',
     'icon': '//cdn.weatherapi.com/weather/64x64/day/353.png',
     'code': 1240},
    'uv': 7.1},
   'astro': {'sunrise': '06:05 AM',
    'sunset': '06:24 PM',
    'moonrise': '10:35 AM',
    'moonset': '10:54 PM',
    'moon_phase': 'First Quarter',
    'moon_illumination': 33,
    'is_moon_up': 1,
    'is_sun_up': 1},
   'hour': [{'time_epoch': 1784437200,
     'time': '2026-07-19 00:00',
     'temp_c': 23.9,
     'temp_f': 75.0,
     'is_day': 0,
     'condition': {'text': 'Light rain shower',
      'icon': '//cdn.weatherapi.com/weather/64x64/night/353.png',
      'code': 1240},
     'wind_mph': 2.5,
     'wind_kph': 4.0,
     'wind_degree': 136,
     'wind_dir': 'SE',
     'pressure_mb': 1011.0,
     'pressure_in': 29.85,
     'precip_mm': 0.5,
     'precip_in': 0.02,
     'snow_cm': 0.0,
     'humidity': 93,
     'cloud': 92,
     'feelslike_c': 26.4,
     'feelslike_f': 79.5,
     'windchill_c': 23.9,
     'windchill_f': 75.0,
     'heatindex_c': 26.4,
     'heatindex_f': 79.5,
     'dewpoint_c': 22.8,
     'dewpoint_f': 73.0,
     'will_it_rain': 0,
     'chance_of_rain': 62,
     'will_it_snow': 0,
     'chance_of_snow': 0,
     'vis_km': 10.0,
     'vis_miles': 6.0,
     'gust_mph': 4.5,
     'gust_kph': 7.2,
     'uv': 0,
     'short_rad': 0,
     'diff_rad': 0,
     'dni': 0,
     'gti': 0},
    {'time_epoch': 1784440800,
     'time': '2026-07-19 01:00',
     'temp_c': 23.8,
     'temp_f': 74.9,
     'is_day': 0,
     'condition': {'text': 'Cloudy',
      'icon': '//cdn.weatherapi.com/weather/64x64/night/119.png',
      'code': 1006},
     'wind_mph': 2.9,
     'wind_kph': 4.7,
     'wind_degree': 152,
     'wind_dir': 'SSE',
     'pressure_mb': 1010.0,
     'pressure_in': 29.83,
     'precip_mm': 0.0,
     'precip_in': 0.0,
     'snow_cm': 0.0,
     'humidity': 93,
     'cloud': 77,
     'feelslike_c': 26.3,
     'feelslike_f': 79.3,
     'windchill_c': 23.8,
     'windchill_f': 74.9,
     'heatindex_c': 26.3,
     'heatindex_f': 79.3,
     'dewpoint_c': 22.7,
     'dewpoint_f': 72.8,
     'will_it_rain': 0,
     'chance_of_rain': 26,
     'will_it_snow': 0,
     'chance_of_snow': 0,
     'vis_km': 10.0,
     'vis_miles': 6.0,
     'gust_mph': 5.3,
     'gust_kph': 8.5,
     'uv': 0,
     'short_rad': 0,
     'diff_rad': 0,
     'dni': 0,
     'gti': 0},
    {'time_epoch': 1784444400,
     'time': '2026-07-19 02:00',
     'temp_c': 23.7,
     'temp_f': 74.7,
     'is_day': 0,
     'condition': {'text': 'Cloudy',
      'icon': '//cdn.weatherapi.com/weather/64x64/night/119.png',
      'code': 1006},
     'wind_mph': 2.7,
     'wind_kph': 4.3,
     'wind_degree': 167,
     'wind_dir': 'SSE',
     'pressure_mb': 1010.0,
     'pressure_in': 29.81,
     'precip_mm': 0.0,
     'precip_in': 0.0,
     'snow_cm': 0.0,
     'humidity': 93,
     'cloud': 73,
     'feelslike_c': 26.1,
     'feelslike_f': 79.0,
     'windchill_c': 23.7,
     'windchill_f': 74.7,
     'heatindex_c': 26.1,
     'heatindex_f': 79.0,
     'dewpoint_c': 22.5,
     'dewpoint_f': 72.5,
     'will_it_rain': 0,
     'chance_of_rain': 25,
     'will_it_snow': 0,
     'chance_of_snow': 0,
     'vis_km': 10.0,
     'vis_miles': 6.0,
     'gust_mph': 4.9,
     'gust_kph': 7.9,
     'uv': 0,
     'short_rad': 0,
     'diff_rad': 0,
     'dni': 0,
     'gti': 0},
    {'time_epoch': 1784448000,
     'time': '2026-07-19 03:00',
     'temp_c': 23.8,
     'temp_f': 74.9,
     'is_day': 0,
     'condition': {'text': 'Patchy rain nearby',
      'icon': '//cdn.weatherapi.com/weather/64x64/night/176.png',
      'code': 1063},
     'wind_mph': 2.2,
     'wind_kph': 3.6,
     'wind_degree': 178,
     'wind_dir': 'S',
     'pressure_mb': 1009.0,
     'pressure_in': 29.8,
     'precip_mm': 0.01,
     'precip_in': 0.0,
     'snow_cm': 0.0,
     'humidity': 93,
     'cloud': 73,
     'feelslike_c': 26.3,
     'feelslike_f': 79.3,
     'windchill_c': 23.8,
     'windchill_f': 74.9,
     'heatindex_c': 26.3,
     'heatindex_f': 79.3,
     'dewpoint_c': 22.6,
     'dewpoint_f': 72.7,
     'will_it_rain': 0,
     'chance_of_rain': 26,
     'will_it_snow': 0,
     'chance_of_snow': 0,
     'vis_km': 10.0,
     'vis_miles': 6.0,
     'gust_mph': 4.0,
     'gust_kph': 6.4,
     'uv': 0,
     'short_rad': 0,
     'diff_rad': 0,
     'dni': 0,
     'gti': 0},
    {'time_epoch': 1784451600,
     'time': '2026-07-19 04:00',
     'temp_c': 23.8,
     'temp_f': 74.9,
     'is_day': 0,
     'condition': {'text': 'Light rain shower',
      'icon': '//cdn.weatherapi.com/weather/64x64/night/353.png',
      'code': 1240},
     'wind_mph': 5.8,
     'wind_kph': 9.4,
     'wind_degree': 189,
     'wind_dir': 'S',
     'pressure_mb': 1009.0,
     'pressure_in': 29.79,
     'precip_mm': 0.45,
     'precip_in': 0.02,
     'snow_cm': 0.0,
     'humidity': 95,
     'cloud': 93,
     'feelslike_c': 26.4,
     'feelslike_f': 79.4,
     'windchill_c': 23.8,
     'windchill_f': 74.9,
     'heatindex_c': 26.4,
     'heatindex_f': 79.4,
     'dewpoint_c': 23.0,
     'dewpoint_f': 73.3,
     'will_it_rain': 0,
     'chance_of_rain': 60,
     'will_it_snow': 0,
     'chance_of_snow': 0,
     'vis_km': 10.0,
     'vis_miles': 6.0,
     'gust_mph': 9.8,
     'gust_kph': 15.7,
     'uv': 0,
     'short_rad': 0,
     'diff_rad': 0,
     'dni': 0,
     'gti': 0},
    {'time_epoch': 1784455200,
     'time': '2026-07-19 05:00',
     'temp_c': 23.8,
     'temp_f': 74.8,
     'is_day': 0,
     'condition': {'text': 'Light rain shower',
      'icon': '//cdn.weatherapi.com/weather/64x64/night/353.png',
      'code': 1240},
     'wind_mph': 4.7,
     'wind_kph': 7.6,
     'wind_degree': 187,
     'wind_dir': 'S',
     'pressure_mb': 1009.0,
     'pressure_in': 29.8,
     'precip_mm': 0.68,
     'precip_in': 0.03,
     'snow_cm': 0.0,
     'humidity': 95,
     'cloud': 89,
     'feelslike_c': 26.3,
     'feelslike_f': 79.4,
     'windchill_c': 23.8,
     'windchill_f': 74.8,
     'heatindex_c': 26.3,
     'heatindex_f': 79.4,
     'dewpoint_c': 23.0,
     'dewpoint_f': 73.3,
     'will_it_rain': 0,
     'chance_of_rain': 66,
     'will_it_snow': 0,
     'chance_of_snow': 0,
     'vis_km': 10.0,
     'vis_miles': 6.0,
     'gust_mph': 7.8,
     'gust_kph': 12.5,
     'uv': 0,
     'short_rad': 0,
     'diff_rad': 0,
     'dni': 0,
     'gti': 0},
    {'time_epoch': 1784458800,
     'time': '2026-07-19 06:00',
     'temp_c': 23.7,
     'temp_f': 74.6,
     'is_day': 0,
     'condition': {'text': 'Light rain shower',
      'icon': '//cdn.weatherapi.com/weather/64x64/night/353.png',
      'code': 1240},
     'wind_mph': 4.5,
     'wind_kph': 7.2,
     'wind_degree': 174,
     'wind_dir': 'S',
     'pressure_mb': 1010.0,
     'pressure_in': 29.81,
     'precip_mm': 1.47,
     'precip_in': 0.06,
     'snow_cm': 0.0,
     'humidity': 95,
     'cloud': 100,
     'feelslike_c': 26.1,
     'feelslike_f': 79.1,
     'windchill_c': 23.7,
     'windchill_f': 74.6,
     'heatindex_c': 26.1,
     'heatindex_f': 79.1,
     'dewpoint_c': 22.8,
     'dewpoint_f': 73.0,
     'will_it_rain': 1,
     'chance_of_rain': 79,
     'will_it_snow': 0,
     'chance_of_snow': 0,
     'vis_km': 10.0,
     'vis_miles': 6.0,
     'gust_mph': 8.1,
     'gust_kph': 13.1,
     'uv': 0,
     'short_rad': 0,
     'diff_rad': 0,
     'dni': 0,
     'gti': 0},
    {'time_epoch': 1784462400,
     'time': '2026-07-19 07:00',
     'temp_c': 24.1,
     'temp_f': 75.3,
     'is_day': 1,
     'condition': {'text': 'Light rain shower',
      'icon': '//cdn.weatherapi.com/weather/64x64/day/353.png',
      'code': 1240},
     'wind_mph': 2.7,
     'wind_kph': 4.3,
     'wind_degree': 174,
     'wind_dir': 'S',
     'pressure_mb': 1010.0,
     'pressure_in': 29.83,
     'precip_mm': 1.07,
     'precip_in': 0.04,
     'snow_cm': 0.0,
     'humidity': 95,
     'cloud': 93,
     'feelslike_c': 26.7,
     'feelslike_f': 80.0,
     'windchill_c': 24.1,
     'windchill_f': 75.3,
     'heatindex_c': 26.7,
     'heatindex_f': 80.0,
     'dewpoint_c': 23.1,
     'dewpoint_f': 73.7,
     'will_it_rain': 1,
     'chance_of_rain': 75,
     'will_it_snow': 0,
     'chance_of_snow': 0,
     'vis_km': 10.0,
     'vis_miles': 6.0,
     'gust_mph': 4.5,
     'gust_kph': 7.3,
     'uv': 0.4,
     'short_rad': 2.06,
     'diff_rad': 1.16,
     'dni': 0.0,
     'gti': 0.0},
    {'time_epoch': 1784466000,
     'time': '2026-07-19 08:00',
     'temp_c': 25.1,
     'temp_f': 77.2,
     'is_day': 1,
     'condition': {'text': 'Light rain shower',
      'icon': '//cdn.weatherapi.com/weather/64x64/day/353.png',
      'code': 1240},
     'wind_mph': 3.8,
     'wind_kph': 6.1,
     'wind_degree': 186,
     'wind_dir': 'S',
     'pressure_mb': 1011.0,
     'pressure_in': 29.84,
     'precip_mm': 0.23,
     'precip_in': 0.01,
     'snow_cm': 0.0,
     'humidity': 93,
     'cloud': 72,
     'feelslike_c': 28.2,
     'feelslike_f': 82.7,
     'windchill_c': 25.1,
     'windchill_f': 77.2,
     'heatindex_c': 28.2,
     'heatindex_f': 82.7,
     'dewpoint_c': 23.8,
     'dewpoint_f': 74.9,
     'will_it_rain': 0,
     'chance_of_rain': 41,
     'will_it_snow': 0,
     'chance_of_snow': 0,
     'vis_km': 10.0,
     'vis_miles': 6.0,
     'gust_mph': 5.1,
     'gust_kph': 8.2,
     'uv': 1.3,
     'short_rad': 134.26,
     'diff_rad': 73.43,
     'dni': 0.0,
     'gti': 0.0},
    {'time_epoch': 1784469600,
     'time': '2026-07-19 09:00',
     'temp_c': 26.0,
     'temp_f': 78.8,
     'is_day': 1,
     'condition': {'text': 'Light rain shower',
      'icon': '//cdn.weatherapi.com/weather/64x64/day/353.png',
      'code': 1240},
     'wind_mph': 4.5,
     'wind_kph': 7.2,
     'wind_degree': 214,
     'wind_dir': 'SW',
     'pressure_mb': 1011.0,
     'pressure_in': 29.85,
     'precip_mm': 0.52,
     'precip_in': 0.02,
     'snow_cm': 0.0,
     'humidity': 89,
     'cloud': 76,
     'feelslike_c': 29.5,
     'feelslike_f': 85.0,
     'windchill_c': 26.0,
     'windchill_f': 78.8,
     'heatindex_c': 29.5,
     'heatindex_f': 85.0,
     'dewpoint_c': 24.1,
     'dewpoint_f': 75.3,
     'will_it_rain': 0,
     'chance_of_rain': 55,
     'will_it_snow': 0,
     'chance_of_snow': 0,
     'vis_km': 10.0,
     'vis_miles': 6.0,
     'gust_mph': 6.1,
     'gust_kph': 9.9,
     'uv': 3.5,
     'short_rad': 224.98,
     'diff_rad': 121.89,
     'dni': 0.0,
     'gti': 0.0},
    {'time_epoch': 1784473200,
     'time': '2026-07-19 10:00',
     'temp_c': 27.0,
     'temp_f': 80.6,
     'is_day': 1,
     'condition': {'text': 'Light rain shower',
      'icon': '//cdn.weatherapi.com/weather/64x64/day/353.png',
      'code': 1240},
     'wind_mph': 5.4,
     'wind_kph': 8.6,
     'wind_degree': 221,
     'wind_dir': 'SW',
     'pressure_mb': 1011.0,
     'pressure_in': 29.87,
     'precip_mm': 1.73,
     'precip_in': 0.07,
     'snow_cm': 0.0,
     'humidity': 85,
     'cloud': 56,
     'feelslike_c': 31.0,
     'feelslike_f': 87.8,
     'windchill_c': 27.0,
     'windchill_f': 80.6,
     'heatindex_c': 31.0,
     'heatindex_f': 87.8,
     'dewpoint_c': 24.4,
     'dewpoint_f': 75.8,
     'will_it_rain': 0,
     'chance_of_rain': 65,
     'will_it_snow': 0,
     'chance_of_snow': 0,
     'vis_km': 10.0,
     'vis_miles': 6.0,
     'gust_mph': 8.8,
     'gust_kph': 14.2,
     'uv': 6.0,
     'short_rad': 322.56,
     'diff_rad': 168.88,
     'dni': 9.57,
     'gti': 322.44},
    {'time_epoch': 1784476800,
     'time': '2026-07-19 11:00',
     'temp_c': 27.3,
     'temp_f': 81.1,
     'is_day': 1,
     'condition': {'text': 'Light rain shower',
      'icon': '//cdn.weatherapi.com/weather/64x64/day/353.png',
      'code': 1240},
     'wind_mph': 6.3,
     'wind_kph': 10.1,
     'wind_degree': 225,
     'wind_dir': 'SW',
     'pressure_mb': 1011.0,
     'pressure_in': 29.85,
     'precip_mm': 1.0,
     'precip_in': 0.04,
     'snow_cm': 0.0,
     'humidity': 83,
     'cloud': 61,
     'feelslike_c': 31.3,
     'feelslike_f': 88.4,
     'windchill_c': 27.3,
     'windchill_f': 81.1,
     'heatindex_c': 31.3,
     'heatindex_f': 88.4,
     'dewpoint_c': 24.3,
     'dewpoint_f': 75.7,
     'will_it_rain': 0,
     'chance_of_rain': 59,
     'will_it_snow': 0,
     'chance_of_snow': 0,
     'vis_km': 10.0,
     'vis_miles': 6.0,
     'gust_mph': 10.8,
     'gust_kph': 17.3,
     'uv': 6.8,
     'short_rad': 364.75,
     'diff_rad': 194.97,
     'dni': 16.88,
     'gti': 364.73},
    {'time_epoch': 1784480400,
     'time': '2026-07-19 12:00',
     'temp_c': 26.9,
     'temp_f': 80.5,
     'is_day': 1,
     'condition': {'text': 'Light rain shower',
      'icon': '//cdn.weatherapi.com/weather/64x64/day/353.png',
      'code': 1240},
     'wind_mph': 7.2,
     'wind_kph': 11.5,
     'wind_degree': 246,
     'wind_dir': 'WSW',
     'pressure_mb': 1011.0,
     'pressure_in': 29.85,
     'precip_mm': 1.91,
     'precip_in': 0.08,
     'snow_cm': 0.0,
     'humidity': 87,
     'cloud': 77,
     'feelslike_c': 31.0,
     'feelslike_f': 87.8,
     'windchill_c': 26.9,
     'windchill_f': 80.5,
     'heatindex_c': 31.0,
     'heatindex_f': 87.8,
     'dewpoint_c': 24.5,
     'dewpoint_f': 76.2,
     'will_it_rain': 1,
     'chance_of_rain': 72,
     'will_it_snow': 0,
     'chance_of_snow': 0,
     'vis_km': 10.0,
     'vis_miles': 6.0,
     'gust_mph': 13.7,
     'gust_kph': 22.0,
     'uv': 7.1,
     'short_rad': 380.93,
     'diff_rad': 206.93,
     'dni': 20.95,
     'gti': 380.97},
    {'time_epoch': 1784484000,
     'time': '2026-07-19 13:00',
     'temp_c': 26.5,
     'temp_f': 79.8,
     'is_day': 1,
     'condition': {'text': 'Light rain shower',
      'icon': '//cdn.weatherapi.com/weather/64x64/day/353.png',
      'code': 1240},
     'wind_mph': 5.8,
     'wind_kph': 9.4,
     'wind_degree': 244,
     'wind_dir': 'WSW',
     'pressure_mb': 1010.0,
     'pressure_in': 29.83,
     'precip_mm': 1.74,
     'precip_in': 0.07,
     'snow_cm': 0.0,
     'humidity': 88,
     'cloud': 75,
     'feelslike_c': 30.4,
     'feelslike_f': 86.7,
     'windchill_c': 26.5,
     'windchill_f': 79.8,
     'heatindex_c': 30.4,
     'heatindex_f': 86.7,
     'dewpoint_c': 24.4,
     'dewpoint_f': 75.9,
     'will_it_rain': 1,
     'chance_of_rain': 71,
     'will_it_snow': 0,
     'chance_of_snow': 0,
     'vis_km': 10.0,
     'vis_miles': 6.0,
     'gust_mph': 11.4,
     'gust_kph': 18.4,
     'uv': 5.8,
     'short_rad': 384.45,
     'diff_rad': 211.26,
     'dni': 21.94,
     'gti': 384.5},
    {'time_epoch': 1784487600,
     'time': '2026-07-19 14:00',
     'temp_c': 26.3,
     'temp_f': 79.3,
     'is_day': 1,
     'condition': {'text': 'Light rain shower',
      'icon': '//cdn.weatherapi.com/weather/64x64/day/353.png',
      'code': 1240},
     'wind_mph': 4.9,
     'wind_kph': 7.9,
     'wind_degree': 237,
     'wind_dir': 'WSW',
     'pressure_mb': 1010.0,
     'pressure_in': 29.81,
     'precip_mm': 1.68,
     'precip_in': 0.07,
     'snow_cm': 0.0,
     'humidity': 89,
     'cloud': 86,
     'feelslike_c': 30.0,
     'feelslike_f': 85.9,
     'windchill_c': 26.3,
     'windchill_f': 79.3,
     'heatindex_c': 30.0,
     'heatindex_f': 85.9,
     'dewpoint_c': 24.3,
     'dewpoint_f': 75.8,
     'will_it_rain': 1,
     'chance_of_rain': 74,
     'will_it_snow': 0,
     'chance_of_snow': 0,
     'vis_km': 10.0,
     'vis_miles': 6.0,
     'gust_mph': 7.1,
     'gust_kph': 11.4,
     'uv': 4.1,
     'short_rad': 385.22,
     'diff_rad': 224.26,
     'dni': 22.16,
     'gti': 385.28},
    {'time_epoch': 1784491200,
     'time': '2026-07-19 15:00',
     'temp_c': 26.1,
     'temp_f': 78.9,
     'is_day': 1,
     'condition': {'text': 'Light rain shower',
      'icon': '//cdn.weatherapi.com/weather/64x64/day/353.png',
      'code': 1240},
     'wind_mph': 4.3,
     'wind_kph': 6.8,
     'wind_degree': 229,
     'wind_dir': 'SW',
     'pressure_mb': 1009.0,
     'pressure_in': 29.79,
     'precip_mm': 1.64,
     'precip_in': 0.06,
     'snow_cm': 0.0,
     'humidity': 90,
     'cloud': 86,
     'feelslike_c': 29.6,
     'feelslike_f': 85.3,
     'windchill_c': 26.1,
     'windchill_f': 78.9,
     'heatindex_c': 29.6,
     'heatindex_f': 85.3,
     'dewpoint_c': 24.2,
     'dewpoint_f': 75.6,
     'will_it_rain': 1,
     'chance_of_rain': 74,
     'will_it_snow': 0,
     'chance_of_snow': 0,
     'vis_km': 10.0,
     'vis_miles': 6.0,
     'gust_mph': 5.8,
     'gust_kph': 9.4,
     'uv': 2.5,
     'short_rad': 337.04,
     'diff_rad': 197.13,
     'dni': 11.59,
     'gti': 336.94},
    {'time_epoch': 1784494800,
     'time': '2026-07-19 16:00',
     'temp_c': 25.8,
     'temp_f': 78.5,
     'is_day': 1,
     'condition': {'text': 'Light rain shower',
      'icon': '//cdn.weatherapi.com/weather/64x64/day/353.png',
      'code': 1240},
     'wind_mph': 3.4,
     'wind_kph': 5.4,
     'wind_degree': 217,
     'wind_dir': 'SW',
     'pressure_mb': 1009.0,
     'pressure_in': 29.79,
     'precip_mm': 1.43,
     'precip_in': 0.06,
     'snow_cm': 0.0,
     'humidity': 90,
     'cloud': 94,
     'feelslike_c': 29.3,
     'feelslike_f': 84.7,
     'windchill_c': 25.9,
     'windchill_f': 78.5,
     'heatindex_c': 29.3,
     'heatindex_f': 84.7,
     'dewpoint_c': 24.2,
     'dewpoint_f': 75.5,
     'will_it_rain': 1,
     'chance_of_rain': 75,
     'will_it_snow': 0,
     'chance_of_snow': 0,
     'vis_km': 10.0,
     'vis_miles': 6.0,
     'gust_mph': 6.1,
     'gust_kph': 9.9,
     'uv': 1.1,
     'short_rad': 288.3,
     'diff_rad': 168.62,
     'dni': 6.42,
     'gti': 288.15},
    {'time_epoch': 1784498400,
     'time': '2026-07-19 17:00',
     'temp_c': 26.2,
     'temp_f': 79.2,
     'is_day': 1,
     'condition': {'text': 'Partly cloudy',
      'icon': '//cdn.weatherapi.com/weather/64x64/day/116.png',
      'code': 1003},
     'wind_mph': 2.9,
     'wind_kph': 4.7,
     'wind_degree': 203,
     'wind_dir': 'SSW',
     'pressure_mb': 1009.0,
     'pressure_in': 29.8,
     'precip_mm': 1.1,
     'precip_in': 0.04,
     'snow_cm': 0.0,
     'humidity': 94,
     'cloud': 50,
     'feelslike_c': 28.8,
     'feelslike_f': 83.9,
     'windchill_c': 25.6,
     'windchill_f': 78.0,
     'heatindex_c': 28.8,
     'heatindex_f': 83.9,
     'dewpoint_c': 24.0,
     'dewpoint_f': 75.3,
     'will_it_rain': 1,
     'chance_of_rain': 74,
     'will_it_snow': 0,
     'chance_of_snow': 0,
     'vis_km': 10.0,
     'vis_miles': 6.0,
     'gust_mph': 4.1,
     'gust_kph': 6.7,
     'uv': 0.3,
     'short_rad': 241.87,
     'diff_rad': 141.26,
     'dni': 4.37,
     'gti': 241.73},
    {'time_epoch': 1784502000,
     'time': '2026-07-19 18:00',
     'temp_c': 24.5,
     'temp_f': 76.1,
     'is_day': 1,
     'condition': {'text': 'Light rain shower',
      'icon': '//cdn.weatherapi.com/weather/64x64/day/353.png',
      'code': 1240},
     'wind_mph': 3.4,
     'wind_kph': 5.4,
     'wind_degree': 203,
     'wind_dir': 'SSW',
     'pressure_mb': 1010.0,
     'pressure_in': 29.81,
     'precip_mm': 1.05,
     'precip_in': 0.04,
     'snow_cm': 0.0,
     'humidity': 92,
     'cloud': 100,
     'feelslike_c': 27.2,
     'feelslike_f': 80.9,
     'windchill_c': 24.5,
     'windchill_f': 76.1,
     'heatindex_c': 27.2,
     'heatindex_f': 80.9,
     'dewpoint_c': 23.1,
     'dewpoint_f': 73.6,
     'will_it_rain': 1,
     'chance_of_rain': 74,
     'will_it_snow': 0,
     'chance_of_snow': 0,
     'vis_km': 10.0,
     'vis_miles': 6.0,
     'gust_mph': 6.7,
     'gust_kph': 10.8,
     'uv': 0.0,
     'short_rad': 200.29,
     'diff_rad': 116.99,
     'dni': 2.99,

In [12]:
response['forecast'].keys()

dict_keys(['forecastday'])

In [13]:
response['forecast']['forecastday']

[{'date': '2026-07-19',
  'date_epoch': 1784419200,
  'day': {'maxtemp_c': 27.3,
   'maxtemp_f': 81.1,
   'mintemp_c': 23.7,
   'mintemp_f': 74.6,
   'avgtemp_c': 24.9,
   'avgtemp_f': 76.8,
   'maxwind_mph': 7.2,
   'maxwind_kph': 11.5,
   'totalprecip_mm': 24.59,
   'totalprecip_in': 0.97,
   'totalsnow_cm': 0.0,
   'avgvis_km': 9.9,
   'avgvis_miles': 6.0,
   'avghumidity': 92,
   'daily_will_it_rain': 1,
   'daily_chance_of_rain': 90,
   'daily_will_it_snow': 0,
   'daily_chance_of_snow': 0,
   'condition': {'text': 'Light rain shower',
    'icon': '//cdn.weatherapi.com/weather/64x64/day/353.png',
    'code': 1240},
   'uv': 7.1},
  'astro': {'sunrise': '06:05 AM',
   'sunset': '06:24 PM',
   'moonrise': '10:35 AM',
   'moonset': '10:54 PM',
   'moon_phase': 'First Quarter',
   'moon_illumination': 33,
   'is_moon_up': 1,
   'is_sun_up': 1},
  'hour': [{'time_epoch': 1784437200,
    'time': '2026-07-19 00:00',
    'temp_c': 23.9,
    'temp_f': 75.0,
    'is_day': 0,
    'condition': {'text': 'Light rain shower',
     'icon': '//cdn.weatherapi.com/weather/64x64/night/353.png',
     'code': 1240},
    'wind_mph': 2.5,
    'wind_kph': 4.0,
    'wind_degree': 136,
    'wind_dir': 'SE',
    'pressure_mb': 1011.0,
    'pressure_in': 29.85,
    'precip_mm': 0.5,
    'precip_in': 0.02,
    'snow_cm': 0.0,
    'humidity': 93,
    'cloud': 92,
    'feelslike_c': 26.4,
    'feelslike_f': 79.5,
    'windchill_c': 23.9,
    'windchill_f': 75.0,
    'heatindex_c': 26.4,
    'heatindex_f': 79.5,
    'dewpoint_c': 22.8,
    'dewpoint_f': 73.0,
    'will_it_rain': 0,
    'chance_of_rain': 62,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 10.0,
    'vis_miles': 6.0,
    'gust_mph': 4.5,
    'gust_kph': 7.2,
    'uv': 0,
    'short_rad': 0,
    'diff_rad': 0,
    'dni': 0,
    'gti': 0},
   {'time_epoch': 1784440800,
    'time': '2026-07-19 01:00',
    'temp_c': 23.8,
    'temp_f': 74.9,
    'is_day': 0,
    'condition': {'text': 'Cloudy',
     'icon': '//cdn.weatherapi.com/weather/64x64/night/119.png',
     'code': 1006},
    'wind_mph': 2.9,
    'wind_kph': 4.7,
    'wind_degree': 152,
    'wind_dir': 'SSE',
    'pressure_mb': 1010.0,
    'pressure_in': 29.83,
    'precip_mm': 0.0,
    'precip_in': 0.0,
    'snow_cm': 0.0,
    'humidity': 93,
    'cloud': 77,
    'feelslike_c': 26.3,
    'feelslike_f': 79.3,
    'windchill_c': 23.8,
    'windchill_f': 74.9,
    'heatindex_c': 26.3,
    'heatindex_f': 79.3,
    'dewpoint_c': 22.7,
    'dewpoint_f': 72.8,
    'will_it_rain': 0,
    'chance_of_rain': 26,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 10.0,
    'vis_miles': 6.0,
    'gust_mph': 5.3,
    'gust_kph': 8.5,
    'uv': 0,
    'short_rad': 0,
    'diff_rad': 0,
    'dni': 0,
    'gti': 0},
   {'time_epoch': 1784444400,
    'time': '2026-07-19 02:00',
    'temp_c': 23.7,
    'temp_f': 74.7,
    'is_day': 0,
    'condition': {'text': 'Cloudy',
     'icon': '//cdn.weatherapi.com/weather/64x64/night/119.png',
     'code': 1006},
    'wind_mph': 2.7,
    'wind_kph': 4.3,
    'wind_degree': 167,
    'wind_dir': 'SSE',
    'pressure_mb': 1010.0,
    'pressure_in': 29.81,
    'precip_mm': 0.0,
    'precip_in': 0.0,
    'snow_cm': 0.0,
    'humidity': 93,
    'cloud': 73,
    'feelslike_c': 26.1,
    'feelslike_f': 79.0,
    'windchill_c': 23.7,
    'windchill_f': 74.7,
    'heatindex_c': 26.1,
    'heatindex_f': 79.0,
    'dewpoint_c': 22.5,
    'dewpoint_f': 72.5,
    'will_it_rain': 0,
    'chance_of_rain': 25,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 10.0,
    'vis_miles': 6.0,
    'gust_mph': 4.9,
    'gust_kph': 7.9,
    'uv': 0,
    'short_rad': 0,
    'diff_rad': 0,
    'dni': 0,
    'gti': 0},
   {'time_epoch': 1784448000,
    'time': '2026-07-19 03:00',
    'temp_c': 23.8,
    'temp_f': 74.9,
    'is_day': 0,
    'condition': {'text': 'Patchy rain nearby',
     'icon': '//cdn.weatherapi.com/weather/64x64/night/176.png',
     'code': 1063},
    'wind_mph': 2.2,
    'wind_kph': 3.6,
    'wind_degree': 178,
    'wind_dir': 'S',
    'pressure_mb': 1009.0,
    'pressure_in': 29.8,
    'precip_mm': 0.01,
    'precip_in': 0.0,
    'snow_cm': 0.0,
    'humidity': 93,
    'cloud': 73,
    'feelslike_c': 26.3,
    'feelslike_f': 79.3,
    'windchill_c': 23.8,
    'windchill_f': 74.9,
    'heatindex_c': 26.3,
    'heatindex_f': 79.3,
    'dewpoint_c': 22.6,
    'dewpoint_f': 72.7,
    'will_it_rain': 0,
    'chance_of_rain': 26,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 10.0,
    'vis_miles': 6.0,
    'gust_mph': 4.0,
    'gust_kph': 6.4,
    'uv': 0,
    'short_rad': 0,
    'diff_rad': 0,
    'dni': 0,
    'gti': 0},
   {'time_epoch': 1784451600,
    'time': '2026-07-19 04:00',
    'temp_c': 23.8,
    'temp_f': 74.9,
    'is_day': 0,
    'condition': {'text': 'Light rain shower',
     'icon': '//cdn.weatherapi.com/weather/64x64/night/353.png',
     'code': 1240},
    'wind_mph': 5.8,
    'wind_kph': 9.4,
    'wind_degree': 189,
    'wind_dir': 'S',
    'pressure_mb': 1009.0,
    'pressure_in': 29.79,
    'precip_mm': 0.45,
    'precip_in': 0.02,
    'snow_cm': 0.0,
    'humidity': 95,
    'cloud': 93,
    'feelslike_c': 26.4,
    'feelslike_f': 79.4,
    'windchill_c': 23.8,
    'windchill_f': 74.9,
    'heatindex_c': 26.4,
    'heatindex_f': 79.4,
    'dewpoint_c': 23.0,
    'dewpoint_f': 73.3,
    'will_it_rain': 0,
    'chance_of_rain': 60,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 10.0,
    'vis_miles': 6.0,
    'gust_mph': 9.8,
    'gust_kph': 15.7,
    'uv': 0,
    'short_rad': 0,
    'diff_rad': 0,
    'dni': 0,
    'gti': 0},
   {'time_epoch': 1784455200,
    'time': '2026-07-19 05:00',
    'temp_c': 23.8,
    'temp_f': 74.8,
    'is_day': 0,
    'condition': {'text': 'Light rain shower',
     'icon': '//cdn.weatherapi.com/weather/64x64/night/353.png',
     'code': 1240},
    'wind_mph': 4.7,
    'wind_kph': 7.6,
    'wind_degree': 187,
    'wind_dir': 'S',
    'pressure_mb': 1009.0,
    'pressure_in': 29.8,
    'precip_mm': 0.68,
    'precip_in': 0.03,
    'snow_cm': 0.0,
    'humidity': 95,
    'cloud': 89,
    'feelslike_c': 26.3,
    'feelslike_f': 79.4,
    'windchill_c': 23.8,
    'windchill_f': 74.8,
    'heatindex_c': 26.3,
    'heatindex_f': 79.4,
    'dewpoint_c': 23.0,
    'dewpoint_f': 73.3,
    'will_it_rain': 0,
    'chance_of_rain': 66,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 10.0,
    'vis_miles': 6.0,
    'gust_mph': 7.8,
    'gust_kph': 12.5,
    'uv': 0,
    'short_rad': 0,
    'diff_rad': 0,
    'dni': 0,
    'gti': 0},
   {'time_epoch': 1784458800,
    'time': '2026-07-19 06:00',
    'temp_c': 23.7,
    'temp_f': 74.6,
    'is_day': 0,
    'condition': {'text': 'Light rain shower',
     'icon': '//cdn.weatherapi.com/weather/64x64/night/353.png',
     'code': 1240},
    'wind_mph': 4.5,
    'wind_kph': 7.2,
    'wind_degree': 174,
    'wind_dir': 'S',
    'pressure_mb': 1010.0,
    'pressure_in': 29.81,
    'precip_mm': 1.47,
    'precip_in': 0.06,
    'snow_cm': 0.0,
    'humidity': 95,
    'cloud': 100,
    'feelslike_c': 26.1,
    'feelslike_f': 79.1,
    'windchill_c': 23.7,
    'windchill_f': 74.6,
    'heatindex_c': 26.1,
    'heatindex_f': 79.1,
    'dewpoint_c': 22.8,
    'dewpoint_f': 73.0,
    'will_it_rain': 1,
    'chance_of_rain': 79,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 10.0,
    'vis_miles': 6.0,
    'gust_mph': 8.1,
    'gust_kph': 13.1,
    'uv': 0,
    'short_rad': 0,
    'diff_rad': 0,
    'dni': 0,
    'gti': 0},
   {'time_epoch': 1784462400,
    'time': '2026-07-19 07:00',
    'temp_c': 24.1,
    'temp_f': 75.3,
    'is_day': 1,
    'condition': {'text': 'Light rain shower',
     'icon': '//cdn.weatherapi.com/weather/64x64/day/353.png',
     'code': 1240},
    'wind_mph': 2.7,
    'wind_kph': 4.3,
    'wind_degree': 174,
    'wind_dir': 'S',
    'pressure_mb': 1010.0,
    'pressure_in': 29.83,
    'precip_mm': 1.07,
    'precip_in': 0.04,
    'snow_cm': 0.0,
    'humidity': 95,
    'cloud': 93,
    'feelslike_c': 26.7,
    'feelslike_f': 80.0,
    'windchill_c': 24.1,
    'windchill_f': 75.3,
    'heatindex_c': 26.7,
    'heatindex_f': 80.0,
    'dewpoint_c': 23.1,
    'dewpoint_f': 73.7,
    'will_it_rain': 1,
    'chance_of_rain': 75,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 10.0,
    'vis_miles': 6.0,
    'gust_mph': 4.5,
    'gust_kph': 7.3,
    'uv': 0.4,
    'short_rad': 2.06,
    'diff_rad': 1.16,
    'dni': 0.0,
    'gti': 0.0},
   {'time_epoch': 1784466000,
    'time': '2026-07-19 08:00',
    'temp_c': 25.1,
    'temp_f': 77.2,
    'is_day': 1,
    'condition': {'text': 'Light rain shower',
     'icon': '//cdn.weatherapi.com/weather/64x64/day/353.png',
     'code': 1240},
    'wind_mph': 3.8,
    'wind_kph': 6.1,
    'wind_degree': 186,
    'wind_dir': 'S',
    'pressure_mb': 1011.0,
    'pressure_in': 29.84,
    'precip_mm': 0.23,
    'precip_in': 0.01,
    'snow_cm': 0.0,
    'humidity': 93,
    'cloud': 72,
    'feelslike_c': 28.2,
    'feelslike_f': 82.7,
    'windchill_c': 25.1,
    'windchill_f': 77.2,
    'heatindex_c': 28.2,
    'heatindex_f': 82.7,
    'dewpoint_c': 23.8,
    'dewpoint_f': 74.9,
    'will_it_rain': 0,
    'chance_of_rain': 41,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 10.0,
    'vis_miles': 6.0,
    'gust_mph': 5.1,
    'gust_kph': 8.2,
    'uv': 1.3,
    'short_rad': 134.26,
    'diff_rad': 73.43,
    'dni': 0.0,
    'gti': 0.0},
   {'time_epoch': 1784469600,
    'time': '2026-07-19 09:00',
    'temp_c': 26.0,
    'temp_f': 78.8,
    'is_day': 1,
    'condition': {'text': 'Light rain shower',
     'icon': '//cdn.weatherapi.com/weather/64x64/day/353.png',
     'code': 1240},
    'wind_mph': 4.5,
    'wind_kph': 7.2,
    'wind_degree': 214,
    'wind_dir': 'SW',
    'pressure_mb': 1011.0,
    'pressure_in': 29.85,
    'precip_mm': 0.52,
    'precip_in': 0.02,
    'snow_cm': 0.0,
    'humidity': 89,
    'cloud': 76,
    'feelslike_c': 29.5,
    'feelslike_f': 85.0,
    'windchill_c': 26.0,
    'windchill_f': 78.8,
    'heatindex_c': 29.5,
    'heatindex_f': 85.0,
    'dewpoint_c': 24.1,
    'dewpoint_f': 75.3,
    'will_it_rain': 0,
    'chance_of_rain': 55,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 10.0,
    'vis_miles': 6.0,
    'gust_mph': 6.1,
    'gust_kph': 9.9,
    'uv': 3.5,
    'short_rad': 224.98,
    'diff_rad': 121.89,
    'dni': 0.0,
    'gti': 0.0},
   {'time_epoch': 1784473200,
    'time': '2026-07-19 10:00',
    'temp_c': 27.0,
    'temp_f': 80.6,
    'is_day': 1,
    'condition': {'text': 'Light rain shower',
     'icon': '//cdn.weatherapi.com/weather/64x64/day/353.png',
     'code': 1240},
    'wind_mph': 5.4,
    'wind_kph': 8.6,
    'wind_degree': 221,
    'wind_dir': 'SW',
    'pressure_mb': 1011.0,
    'pressure_in': 29.87,
    'precip_mm': 1.73,
    'precip_in': 0.07,
    'snow_cm': 0.0,
    'humidity': 85,
    'cloud': 56,
    'feelslike_c': 31.0,
    'feelslike_f': 87.8,
    'windchill_c': 27.0,
    'windchill_f': 80.6,
    'heatindex_c': 31.0,
    'heatindex_f': 87.8,
    'dewpoint_c': 24.4,
    'dewpoint_f': 75.8,
    'will_it_rain': 0,
    'chance_of_rain': 65,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 10.0,
    'vis_miles': 6.0,
    'gust_mph': 8.8,
    'gust_kph': 14.2,
    'uv': 6.0,
    'short_rad': 322.56,
    'diff_rad': 168.88,
    'dni': 9.57,
    'gti': 322.44},
   {'time_epoch': 1784476800,
    'time': '2026-07-19 11:00',
    'temp_c': 27.3,
    'temp_f': 81.1,
    'is_day': 1,
    'condition': {'text': 'Light rain shower',
     'icon': '//cdn.weatherapi.com/weather/64x64/day/353.png',
     'code': 1240},
    'wind_mph': 6.3,
    'wind_kph': 10.1,
    'wind_degree': 225,
    'wind_dir': 'SW',
    'pressure_mb': 1011.0,
    'pressure_in': 29.85,
    'precip_mm': 1.0,
    'precip_in': 0.04,
    'snow_cm': 0.0,
    'humidity': 83,
    'cloud': 61,
    'feelslike_c': 31.3,
    'feelslike_f': 88.4,
    'windchill_c': 27.3,
    'windchill_f': 81.1,
    'heatindex_c': 31.3,
    'heatindex_f': 88.4,
    'dewpoint_c': 24.3,
    'dewpoint_f': 75.7,
    'will_it_rain': 0,
    'chance_of_rain': 59,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 10.0,
    'vis_miles': 6.0,
    'gust_mph': 10.8,
    'gust_kph': 17.3,
    'uv': 6.8,
    'short_rad': 364.75,
    'diff_rad': 194.97,
    'dni': 16.88,
    'gti': 364.73},
   {'time_epoch': 1784480400,
    'time': '2026-07-19 12:00',
    'temp_c': 26.9,
    'temp_f': 80.5,
    'is_day': 1,
    'condition': {'text': 'Light rain shower',
     'icon': '//cdn.weatherapi.com/weather/64x64/day/353.png',
     'code': 1240},
    'wind_mph': 7.2,
    'wind_kph': 11.5,
    'wind_degree': 246,
    'wind_dir': 'WSW',
    'pressure_mb': 1011.0,
    'pressure_in': 29.85,
    'precip_mm': 1.91,
    'precip_in': 0.08,
    'snow_cm': 0.0,
    'humidity': 87,
    'cloud': 77,
    'feelslike_c': 31.0,
    'feelslike_f': 87.8,
    'windchill_c': 26.9,
    'windchill_f': 80.5,
    'heatindex_c': 31.0,
    'heatindex_f': 87.8,
    'dewpoint_c': 24.5,
    'dewpoint_f': 76.2,
    'will_it_rain': 1,
    'chance_of_rain': 72,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 10.0,
    'vis_miles': 6.0,
    'gust_mph': 13.7,
    'gust_kph': 22.0,
    'uv': 7.1,
    'short_rad': 380.93,
    'diff_rad': 206.93,
    'dni': 20.95,
    'gti': 380.97},
   {'time_epoch': 1784484000,
    'time': '2026-07-19 13:00',
    'temp_c': 26.5,
    'temp_f': 79.8,
    'is_day': 1,
    'condition': {'text': 'Light rain shower',
     'icon': '//cdn.weatherapi.com/weather/64x64/day/353.png',
     'code': 1240},
    'wind_mph': 5.8,
    'wind_kph': 9.4,
    'wind_degree': 244,
    'wind_dir': 'WSW',
    'pressure_mb': 1010.0,
    'pressure_in': 29.83,
    'precip_mm': 1.74,
    'precip_in': 0.07,
    'snow_cm': 0.0,
    'humidity': 88,
    'cloud': 75,
    'feelslike_c': 30.4,
    'feelslike_f': 86.7,
    'windchill_c': 26.5,
    'windchill_f': 79.8,
    'heatindex_c': 30.4,
    'heatindex_f': 86.7,
    'dewpoint_c': 24.4,
    'dewpoint_f': 75.9,
    'will_it_rain': 1,
    'chance_of_rain': 71,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 10.0,
    'vis_miles': 6.0,
    'gust_mph': 11.4,
    'gust_kph': 18.4,
    'uv': 5.8,
    'short_rad': 384.45,
    'diff_rad': 211.26,
    'dni': 21.94,
    'gti': 384.5},
   {'time_epoch': 1784487600,
    'time': '2026-07-19 14:00',
    'temp_c': 26.3,
    'temp_f': 79.3,
    'is_day': 1,
    'condition': {'text': 'Light rain shower',
     'icon': '//cdn.weatherapi.com/weather/64x64/day/353.png',
     'code': 1240},
    'wind_mph': 4.9,
    'wind_kph': 7.9,
    'wind_degree': 237,
    'wind_dir': 'WSW',
    'pressure_mb': 1010.0,
    'pressure_in': 29.81,
    'precip_mm': 1.68,
    'precip_in': 0.07,
    'snow_cm': 0.0,
    'humidity': 89,
    'cloud': 86,
    'feelslike_c': 30.0,
    'feelslike_f': 85.9,
    'windchill_c': 26.3,
    'windchill_f': 79.3,
    'heatindex_c': 30.0,
    'heatindex_f': 85.9,
    'dewpoint_c': 24.3,
    'dewpoint_f': 75.8,
    'will_it_rain': 1,
    'chance_of_rain': 74,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 10.0,
    'vis_miles': 6.0,
    'gust_mph': 7.1,
    'gust_kph': 11.4,
    'uv': 4.1,
    'short_rad': 385.22,
    'diff_rad': 224.26,
    'dni': 22.16,
    'gti': 385.28},
   {'time_epoch': 1784491200,
    'time': '2026-07-19 15:00',
    'temp_c': 26.1,
    'temp_f': 78.9,
    'is_day': 1,
    'condition': {'text': 'Light rain shower',
     'icon': '//cdn.weatherapi.com/weather/64x64/day/353.png',
     'code': 1240},
    'wind_mph': 4.3,
    'wind_kph': 6.8,
    'wind_degree': 229,
    'wind_dir': 'SW',
    'pressure_mb': 1009.0,
    'pressure_in': 29.79,
    'precip_mm': 1.64,
    'precip_in': 0.06,
    'snow_cm': 0.0,
    'humidity': 90,
    'cloud': 86,
    'feelslike_c': 29.6,
    'feelslike_f': 85.3,
    'windchill_c': 26.1,
    'windchill_f': 78.9,
    'heatindex_c': 29.6,
    'heatindex_f': 85.3,
    'dewpoint_c': 24.2,
    'dewpoint_f': 75.6,
    'will_it_rain': 1,
    'chance_of_rain': 74,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 10.0,
    'vis_miles': 6.0,
    'gust_mph': 5.8,
    'gust_kph': 9.4,
    'uv': 2.5,
    'short_rad': 337.04,
    'diff_rad': 197.13,
    'dni': 11.59,
    'gti': 336.94},
   {'time_epoch': 1784494800,
    'time': '2026-07-19 16:00',
    'temp_c': 25.8,
    'temp_f': 78.5,
    'is_day': 1,
    'condition': {'text': 'Light rain shower',
     'icon': '//cdn.weatherapi.com/weather/64x64/day/353.png',
     'code': 1240},
    'wind_mph': 3.4,
    'wind_kph': 5.4,
    'wind_degree': 217,
    'wind_dir': 'SW',
    'pressure_mb': 1009.0,
    'pressure_in': 29.79,
    'precip_mm': 1.43,
    'precip_in': 0.06,
    'snow_cm': 0.0,
    'humidity': 90,
    'cloud': 94,
    'feelslike_c': 29.3,
    'feelslike_f': 84.7,
    'windchill_c': 25.9,
    'windchill_f': 78.5,
    'heatindex_c': 29.3,
    'heatindex_f': 84.7,
    'dewpoint_c': 24.2,
    'dewpoint_f': 75.5,
    'will_it_rain': 1,
    'chance_of_rain': 75,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 10.0,
    'vis_miles': 6.0,
    'gust_mph': 6.1,
    'gust_kph': 9.9,
    'uv': 1.1,
    'short_rad': 288.3,
    'diff_rad': 168.62,
    'dni': 6.42,
    'gti': 288.15},
   {'time_epoch': 1784498400,
    'time': '2026-07-19 17:00',
    'temp_c': 26.2,
    'temp_f': 79.2,
    'is_day': 1,
    'condition': {'text': 'Partly cloudy',
     'icon': '//cdn.weatherapi.com/weather/64x64/day/116.png',
     'code': 1003},
    'wind_mph': 2.9,
    'wind_kph': 4.7,
    'wind_degree': 203,
    'wind_dir': 'SSW',
    'pressure_mb': 1009.0,
    'pressure_in': 29.8,
    'precip_mm': 1.1,
    'precip_in': 0.04,
    'snow_cm': 0.0,
    'humidity': 94,
    'cloud': 50,
    'feelslike_c': 28.8,
    'feelslike_f': 83.9,
    'windchill_c': 25.6,
    'windchill_f': 78.0,
    'heatindex_c': 28.8,
    'heatindex_f': 83.9,
    'dewpoint_c': 24.0,
    'dewpoint_f': 75.3,
    'will_it_rain': 1,
    'chance_of_rain': 74,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 10.0,
    'vis_miles': 6.0,
    'gust_mph': 4.1,
    'gust_kph': 6.7,
    'uv': 0.3,
    'short_rad': 241.87,
    'diff_rad': 141.26,
    'dni': 4.37,
    'gti': 241.73},
   {'time_epoch': 1784502000,
    'time': '2026-07-19 18:00',
    'temp_c': 24.5,
    'temp_f': 76.1,
    'is_day': 1,
    'condition': {'text': 'Light rain shower',
     'icon': '//cdn.weatherapi.com/weather/64x64/day/353.png',
     'code': 1240},
    'wind_mph': 3.4,
    'wind_kph': 5.4,
    'wind_degree': 203,
    'wind_dir': 'SSW',
    'pressure_mb': 1010.0,
    'pressure_in': 29.81,
    'precip_mm': 1.05,
    'precip_in': 0.04,
    'snow_cm': 0.0,
    'humidity': 92,
    'cloud': 100,
    'feelslike_c': 27.2,
    'feelslike_f': 80.9,
    'windchill_c': 24.5,
    'windchill_f': 76.1,
    'heatindex_c': 27.2,
    'heatindex_f': 80.9,
    'dewpoint_c': 23.1,
    'dewpoint_f': 73.6,
    'will_it_rain': 1,
    'chance_of_rain': 74,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 10.0,
    'vis_miles': 6.0,
    'gust_mph': 6.7,
    'gust_kph': 10.8,
    'uv': 0.0,
    'short_rad': 200.29,
    'diff_rad': 116.99,
    'dni': 2.99,
    'gti': 200.16},
   {'time_epoch': 1784505600,
    'time': '2026-07-19 19:00',
    'temp_c': 24.1,
    'temp_f': 75.3,
    'is_day': 0,
    'condition': {'text': 'Light rain',
     'icon': '//cdn.weatherapi.com/weather/64x64/night/296.png',
     'code': 1183},
    'wind_mph': 3.4,
    'wind_kph': 5.4,
    'wind_degree': 198,
    'wind_dir': 'SSW',
    'pressure_mb': 1010.0,
    'pressure_in': 29.83,
    'precip_mm': 0.75,
    'precip_in': 0.03,
    'snow_cm': 0.0,
    'humidity': 92,
    'cloud': 100,
    'feelslike_c': 26.5,
    'feelslike_f': 79.8,
    'windchill_c': 24.1,
    'windchill_f': 75.3,
    'heatindex_c': 26.5,
    'heatindex_f': 79.8,
    'dewpoint_c': 22.8,
    'dewpoint_f': 73.0,
    'will_it_rain': 0,
    'chance_of_rain': 70,
    'will_it_snow': 0,
    'chance_of_snow': 0,
    'vis_km': 9.0,

In [14]:
response['forecast']['forecastday'][0].keys()

dict_keys(['date', 'date_epoch', 'day', 'astro', 'hour'])

In [15]:
len(response['forecast']['forecastday'][0]['hour'])

24

In [16]:
response['forecast']['forecastday'][0]['hour'][15]

{'time_epoch': 1784491200,
 'time': '2026-07-19 15:00',
 'temp_c': 26.1,
 'temp_f': 78.9,
 'is_day': 1,
 'condition': {'text': 'Light rain shower',
  'icon': '//cdn.weatherapi.com/weather/64x64/day/353.png',
  'code': 1240},
 'wind_mph': 4.3,
 'wind_kph': 6.8,
 'wind_degree': 229,
 'wind_dir': 'SW',
 'pressure_mb': 1009.0,
 'pressure_in': 29.79,
 'precip_mm': 1.64,
 'precip_in': 0.06,
 'snow_cm': 0.0,
 'humidity': 90,
 'cloud': 86,
 'feelslike_c': 29.6,
 'feelslike_f': 85.3,
 'windchill_c': 26.1,
 'windchill_f': 78.9,
 'heatindex_c': 29.6,
 'heatindex_f': 85.3,
 'dewpoint_c': 24.2,
 'dewpoint_f': 75.6,
 'will_it_rain': 1,
 'chance_of_rain': 74,
 'will_it_snow': 0,
 'chance_of_snow': 0,
 'vis_km': 10.0,
 'vis_miles': 6.0,
 'gust_mph': 5.8,
 'gust_kph': 9.4,
 'uv': 2.5,
 'short_rad': 337.04,
 'diff_rad': 197.13,
 'dni': 11.59,
 'gti': 336.94}

In [17]:
response['forecast']['forecastday'][0]['hour'][15]['time']

'2026-07-19 15:00'

In [18]:
response['forecast']['forecastday'][0]['hour'][15]['time'].split()[0] # Date

'2026-07-19'

In [19]:
int(response['forecast']['forecastday'][0]['hour'][15]['time'].split()[1].split(':')[0]) # Hour

15

In [20]:
response['forecast']['forecastday'][0]['hour'][15]['condition']['text'] # Condition

'Light rain shower'

In [21]:
response['forecast']['forecastday'][0]['hour'][15]['temp_c'] # Temperature

26.1

In [22]:
response['forecast']['forecastday'][0]['hour'][15]['will_it_rain']

1

In [23]:
response['forecast']['forecastday'][0]['hour'][15]['chance_of_rain']

74

## Dataframe

In [24]:
def get_forecast(response, i):
    forecast = response['forecast']['forecastday'][0]['hour'][i]
    
    date = forecast['time'].split()[0]
    hour = int(forecast['time'].split()[1].split(':')[0])
    condition = forecast['condition']['text']
    temperature_c = forecast['temp_c']
    will_it_rain = forecast['will_it_rain'] 
    chance_of_rain = forecast['chance_of_rain'] 

    return date, hour, condition, temperature_c, will_it_rain, chance_of_rain

In [25]:
data = []
size = len(response['forecast']['forecastday'][0]['hour'])

for i in tqdm(range(size), colour = 'green'):
    data.append(get_forecast(response, i))

100%|████████████████████████████| 24/24 [00:00<00:00, 145888.83it/s]

In [26]:
data

[('2026-07-19', 0, 'Light rain shower', 23.9, 0, 62),
 ('2026-07-19', 1, 'Cloudy', 23.8, 0, 26),
 ('2026-07-19', 2, 'Cloudy', 23.7, 0, 25),
 ('2026-07-19', 3, 'Patchy rain nearby', 23.8, 0, 26),
 ('2026-07-19', 4, 'Light rain shower', 23.8, 0, 60),
 ('2026-07-19', 5, 'Light rain shower', 23.8, 0, 66),
 ('2026-07-19', 6, 'Light rain shower', 23.7, 1, 79),
 ('2026-07-19', 7, 'Light rain shower', 24.1, 1, 75),
 ('2026-07-19', 8, 'Light rain shower', 25.1, 0, 41),
 ('2026-07-19', 9, 'Light rain shower', 26.0, 0, 55),
 ('2026-07-19', 10, 'Light rain shower', 27.0, 0, 65),
 ('2026-07-19', 11, 'Light rain shower', 27.3, 0, 59),
 ('2026-07-19', 12, 'Light rain shower', 26.9, 1, 72),
 ('2026-07-19', 13, 'Light rain shower', 26.5, 1, 71),
 ('2026-07-19', 14, 'Light rain shower', 26.3, 1, 74),
 ('2026-07-19', 15, 'Light rain shower', 26.1, 1, 74),
 ('2026-07-19', 16, 'Light rain shower', 25.8, 1, 75),
 ('2026-07-19', 17, 'Partly cloudy', 26.2, 1, 74),
 ('2026-07-19', 18, 'Light rain shower', 24.5, 1, 74),
 ('2026-07-19', 19, 'Light rain', 24.1, 0, 70),
 ('2026-07-19', 20, 'Light rain shower', 23.9, 0, 70),
 ('2026-07-19', 21, 'Light rain', 23.9, 1, 76),
 ('2026-07-19', 22, 'Light rain shower', 23.8, 1, 79),
 ('2026-07-19', 23, 'Light rain', 23.7, 1, 84)]

In [27]:
col = ['Date', 'Hour', 'Condition', 'Temperature(C°)', 'Will_it_rain', 'Chance_of_rain']
df = pd.DataFrame(data, columns = col)
df

,Date,Hour,Condition,Temperature(C°),Will_it_rain,Chance_of_rain
0,2026-07-19,0,Light rain shower,23.9,0,62
1,2026-07-19,1,Cloudy,23.8,0,26
2,2026-07-19,2,Cloudy,23.7,0,25
3,2026-07-19,3,Patchy rain nearby,23.8,0,26
4,2026-07-19,4,Light rain shower,23.8,0,60
5,2026-07-19,5,Light rain shower,23.8,0,66
6,2026-07-19,6,Light rain shower,23.7,1,79
7,2026-07-19,7,Light rain shower,24.1,1,75
8,2026-07-19,8,Light rain shower,25.1,0,41
9,2026-07-19,9,Light rain shower,26.0,0,55
10,2026-07-19,10,Light rain shower,27.0,0,65
11,2026-07-19,11,Light rain shower,27.3,0,59
12,2026-07-19,12,Light rain shower,26.9,1,72
13,2026-07-19,13,Light rain shower,26.5,1,71
14,2026-07-19,14,Light rain shower,26.3,1,74
15,2026-07-19,15,Light rain shower,26.1,1,74
16,2026-07-19,16,Light rain shower,25.8,1,75
17,2026-07-19,17,Partly cloudy,26.2,1,74
18,2026-07-19,18,Light rain shower,24.5,1,74
19,2026-07-19,19,Light rain,24.1,0,70
20,2026-07-19,20,Light rain shower,23.9,0,70
21,2026-07-19,21,Light rain,23.9,1,76
22,2026-07-19,22,Light rain shower,23.8,1,79
23,2026-07-19,23,Light rain,23.7,1,84

In [28]:
START_HOUR = 5
END_HOUR = 22

df_rain = df[
    (df['Will_it_rain'] == 1) & 
    (df['Hour'].between(START_HOUR, END_HOUR))
    ]
df_rain = df_rain[['Hour', 'Condition', 'Chance_of_rain']]
#df_rain.set_index('Hour', inplace = True)
df_rain

    Hour          Condition  Chance_of_rain
6      6  Light rain shower              79
7      7  Light rain shower              75
12    12  Light rain shower              72
13    13  Light rain shower              71
14    14  Light rain shower              74
15    15  Light rain shower              74
16    16  Light rain shower              75
17    17      Partly cloudy              74
18    18  Light rain shower              74
21    21         Light rain              76
22    22  Light rain shower              79

## Message from Twilio

In [29]:
#message_string = '\nHello! \n\n\n Forecast for today '+ df['Date'][0] + ' in '+ query + ' is: \n\n\n' + str(df_rain)

message_string = (
    f'🌧️ Rain expected today in {query}\n'
    f'📅 {df['Date'][0]}\n\n'
)

for _, row in df_rain.iterrows():
    message_string += (
        f'🕒 {row['Hour']:02d}:00 - '
        f'{row['Condition']} '
        f'({row['Chance_of_rain']}%)\n'
    )
    
message_string

'🌧️ Rain expected today in Buenaventura\n📅 2026-07-19\n\n🕒 06:00 - Light rain shower (79%)\n🕒 07:00 - Light rain shower (75%)\n🕒 12:00 - Light rain shower (72%)\n🕒 13:00 - Light rain shower (71%)\n🕒 14:00 - Light rain shower (74%)\n🕒 15:00 - Light rain shower (74%)\n🕒 16:00 - Light rain shower (75%)\n🕒 17:00 - Partly cloudy (74%)\n🕒 18:00 - Light rain shower (74%)\n🕒 21:00 - Light rain (76%)\n🕒 22:00 - Light rain shower (79%)\n'

In [30]:
time.sleep(2)
account_sid = TWILIO_ACCOUNT_SID
auth_token = TWILIO_AUTH_TOKEN

client = Client(account_sid, auth_token)

if df["Will_it_rain"].sum() == 0:
    print('No rain expected today. No message will be sent')

else:
    message = client.messages \
                    .create(
                        body = message_string,
                       from_ = "whatsapp:+14155238886",
                        to = 'whatsapp:'+ PRIVATE_NUMBER
                    )

    print('Message acknowledged ' + message.sid)
    print(message.status)

Message acknowledged SM0e5e2711b84c28b8e4dd7ff9d5855192
queued